/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({

});

Ext.application({
    models: [
        'modelBusesUCR',
        'modelPinesParadas'
    ],
    stores: [
        'storeBusesUCR',
        'storePinesParadas'
    ],
    views: [
        'tabPanelPrincipal',
        'containerInfo',
        'containerDescripProyecto',
        'containerMapaPrinc',
        'mapaDesplieguePines',
        'containerEleccionPines',
        'mapaEleccionPines'
    ],
    name: 'MyApp',

    insertarPinEnMapa: function(lat, lng, idMap, name, boundsObject, iconURL) {
        var point = new google.maps.LatLng(lat,lng);

        if(iconURL!==undefined){
            var iconoPinParada=new google.maps.MarkerImage(iconURL,null,null,null,new google.maps.Size(35,35));
            var marker = new google.maps.Marker({
                map: Ext.getCmp(idMap).getMap(),
                position: point,
                icon: iconoPinParada
            });
        }
        else{
            var marker = new google.maps.Marker({
                map: Ext.getCmp(idMap).getMap(),
                position: point
            });
        }


        //Ext.getCmp(idMap).setMapCenter(point);

        //markersPinesParadas.push(marker);
        boundsObject.extend(point);
        Ext.getCmp(idMap).getMap().fitBounds(boundsObject);
    },

    launch: function() {
        //Array de pines
        //markersPinesParadas=[];
        Ext.create('MyApp.view.tabPanelPrincipal', {fullscreen: true});
    }

});
