/*
 * File: app/view/containerDescripProyecto.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerDescripProyecto', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer',

    config: {
        id: 'containerDescripProyecto',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Sobre este proyecto'
            },
            {
                xtype: 'panel',
                height: '80%',
                html: '<center><font color="gray"><p style="font-size: 150%;">Información general</p><p>&nbsp</p><p style="font-size: 100%;">Bla fasdfadsf fr erj flerj lfej rlfj erlfherl helr fhelrh elr lekr hflerhflekrhf lerh fklerhflke hrlfherl hflehrlfhe rlfh elrh flerhlfherlh felrh flerhflehrlf ehrhelrh felrhflehrfeh rlfh erlfh elrhferlhferklh fekrlh klerhfkl erhflkeh rfklrhe flehrfleh rlkerhfklerhkleh rfl</p></font></center>',
                left: '10%',
                top: '10%',
                width: '80%',
                modal: true,
                scrollable: 'vertical'
            }
        ]
    }

});