/*
 * File: app/view/containerEleccionPines.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerEleccionPines', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer3',

    requires: [
        'MyApp.view.mapaEleccionPines'
    ],

    config: {
        id: 'containerEleccionPines',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Marcar pin',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp('tabPanelPrincipal').setActiveItem(Ext.getCmp('containerInfo'));
                            Ext.getCmp('tabPanelPrincipal').getTabBar().setHidden(0);
                        },
                        right: '3%',
                        width: '20%',
                        text: 'Atrás'
                    }
                ]
            },
            {
                xtype: 'mapaeleccionpines'
            }
        ]
    }

});