/*
 * File: app/view/containerInfo.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.containerInfo', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer11',

    config: {
        id: 'containerInfo',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Información',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //Ext.getCmp('listaDespliegueInfo').removeAll();
                        },
                        right: '3%',
                        width: '18%',
                        iconCls: 'refresh'
                    }
                ]
            },
            {
                xtype: 'container',
                html: '<center><font color="#29088A"><p>&nbsp</p><p>Despliegue por</p></font></center>',
                width: '49%',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            MyApp.app.ejectBotonesDespliegue('parada');
                        },
                        height: '10%',
                        left: '15%',
                        top: '35%',
                        width: '70%',
                        text: 'Paradas'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            MyApp.app.ejectBotonesDespliegue('bus');
                        },
                        height: '10%',
                        left: '15%',
                        top: '55%',
                        width: '70%',
                        text: 'Buses'
                    }
                ]
            },
            {
                xtype: 'container',
                height: '100%',
                left: '49.8%',
                style: 'background-color: black',
                width: '0.4%'
            },
            {
                xtype: 'container',
                height: '100%',
                left: '50.2%',
                width: '49.8%',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'list',
                        id: 'listaDespliegueInfo',
                        emptyText: 'Vacío',
                        itemTpl: [
                            '{Time} {Distance}'
                        ],
                        loadingText: 'Cargando...',
                        store: 'storeDespliegueInfo'
                    }
                ]
            }
        ]
    }

});