/*
 * File: app/store/storeDespliegueInfoBuses.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeDespliegueInfoBuses', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelDespliegueInfoBuses'
    ],

    config: {
        model: 'MyApp.model.modelDespliegueInfoBuses',
        storeId: 'storeDespliegueInfoBuses',
        proxy: {
            type: 'jsonp',
            url: 'http://faraday.eie.ucr.ac.cr/map/php/json_stop_info.php',
            reader: {
                type: 'json',
                rootProperty: 'Faraday'
            }
        }
    }
});