/*
 * File: app/store/storePinesParadas.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storePinesParadas', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelPinesParadas'
    ],

    config: {
        model: 'MyApp.model.modelPinesParadas',
        storeId: 'storePinesParadas',
        proxy: {
            type: 'jsonp',
            url: 'http://faraday.eie.ucr.ac.cr/map/php/json_stop_markers.php',
            reader: {
                type: 'json',
                rootProperty: 'Faraday'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        //while(markersPinesParadas[0]){
        //    markersPinesParadas.pop().setMap(null);
        //}
        limitesPinesParadas = new google.maps.LatLngBounds();

        for(var i=0; i<records.length; i++){
            MyApp.app.insertarPinEnMapa(records[i].get('Latitude'),records[i].get('Longitude'),'mapaDesplieguePines',records[i].get('Name'),limitesPinesParadas,'busstop.png');
        }	
    }

});