/*
 * File: app/store/storeBusesUCR.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeBusesUCR', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelBusesUCR'
    ],

    config: {
        model: 'MyApp.model.modelBusesUCR',
        storeId: 'storeBusesUCR',
        proxy: {
            type: 'jsonp',
            url: 'http://faraday.eie.ucr.ac.cr/map/php/json_bus_markers.php',
            autoAppendParams: false,
            reader: {
                type: 'json',
                idProperty: 'idBus',
                rootProperty: 'Faraday'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        /*
        while(markersPinesBuses[0]){
        markersPinesBuses.pop().setMap(null);
        }
        for(var i=0; i<records.length; i++){
        var j=i+1;
        MyApp.app.insertarPinEnMapa(records[i].get('Latitude'),records[i].get('Longitude'),'mapaDesplieguePines',"Bus "+j,markersPinesBuses,'bus.png');
        }
        */
        if(markersPinesBuses.length===0){
            for(var i=0; i<records.length; i++){
                var j=i+1;
                MyApp.app.insertarPinEnMapa(records[i].get('Latitude'),records[i].get('Longitude'),'mapaDesplieguePines',"Bus "+j,markersPinesBuses,'bus.png');
            }
        }
        else{
            MyApp.app.refrescadoPosMarkers(markersPinesBuses,records);
        }
    }

});