/*
 * File: app/store/storeBusesUCR.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.storeBusesUCR', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.modelBusesUCR'
    ],

    config: {
        model: 'MyApp.model.modelBusesUCR',
        storeId: 'storeBusesUCR',
        proxy: {
            type: 'jsonp',
            url: 'http://186.32.14.67/websites/docs/webpage/map/php/json_bus_markers.php',
            reader: {
                type: 'json',
                idProperty: 'idBus',
                rootProperty: 'Ford'
            }
        },
        listeners: [
            {
                fn: 'onJsonpstoreLoad',
                event: 'load'
            }
        ]
    },

    onJsonpstoreLoad: function(store, records, successful, operation, eOpts) {
        alert('hola papa loca');
        alert(records[0].get('Latitude'));
    }

});